'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
type Stay={id:string;name:string;checkin:string;checkout:string};
export default function Manager(){
 const [stays,setStays]=useState<Stay[]>([]),[name,setName]=useState(''),[checkin,setCheckin]=useState(''),[checkout,setCheckout]=useState(''),[id,setId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[pendingDelete,setPendingDelete]=useState('');
 function load(){return fetch('/api/stays').then(r=>r.json().then((j:unknown)=>{const v=j as {error?:string;stays:{id:string;name:string;checkin:string;checkout:string}[]};if(!r.ok)throw new Error(v.error);setStays(v.stays);})).catch(e=>setMessage((e as Error).message||'Caricamento non riuscito.')).finally(()=>setLoading(false));}
  useEffect(()=>{load();},[]);
 function reset(){setId('');setName('');setCheckin('');setCheckout('');}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/stays',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name,checkin,checkout})});const j=await r.json() as {error?:string;stays:Stay[];stay?:Stay};if(!r.ok)throw new Error(j.error);reset();await load();setMessage('Guida salvata. Puoi copiare il link da inviare agli ospiti.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function link(s:Stay){return window.location.origin+'/?g='+s.id;}
 async function copy(s:Stay){try{await navigator.clipboard.writeText(link(s));setMessage('Link copiato.');}catch{setMessage('Non riesco a copiare automaticamente. Usa il campo del link.');}}
 async function remove(s:Stay){setBusy(true);try{const r=await fetch('/api/stays?id='+s.id,{method:'DELETE'});const j=await r.json() as {error?:string;stays:Stay[];stay?:Stay};if(!r.ok)throw new Error(j.error);if(id===s.id)reset();await load();setPendingDelete('');setMessage('Guida rimossa. Quel link mostrerà la guida generale.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <main className="manager"><header><Link href="/index.html">A Casa di Marco · Guida ospiti</Link><span>Area riservata <button className="text-button logout-button" type="button" onClick={async()=>{await fetch('/api/logout',{method:'POST'});location.reload();}}>Esci</button></span></header><h1>Una guida per i tuoi ospiti</h1><p>Imposta il nome della famiglia o delle persone e invia il loro link. Solo tu puoi modificare questi dati. La guida generale resta rivolta a tutti gli ospiti.</p><form onSubmit={save}><h2>{id?'Modifica la guida':'Crea una guida'}</h2><label>Nome da mostrare<input value={name} onChange={e=>setName(e.target.value)} placeholder="Famiglia Rossi oppure Anna e Luca" maxLength={100} required/></label><div className="dates"><label>Check-in <small>facoltativo</small><input type="date" value={checkin} onChange={e=>setCheckin(e.target.value)}/></label><label>Check-out <small>facoltativo</small><input type="date" value={checkout} onChange={e=>setCheckout(e.target.value)}/></label></div><p className="hint">Le date servono a mostrare la fase del soggiorno e i promemoria. Puoi lasciare entrambe vuote.</p><div className="actions"><button disabled={busy}>{busy?'Salvataggio…':id?'Salva modifiche':'Crea e salva'}</button>{id&&<button className="secondary" type="button" onClick={reset}>Annulla modifica</button>}</div></form><p role="status" className="status">{message}</p><h2>Guide personalizzate</h2>{loading?<p>Caricamento…</p>:!stays.length?<p>Nessuna guida personalizzata. Il link generale mostra già la guida per tutti gli ospiti.</p>:stays.map(s=><article key={s.id}><h3>{s.name}</h3>{s.checkin&&<p>{s.checkin.split('-').reverse().join('/')} – {s.checkout.split('-').reverse().join('/')}</p>}<label className="link-label">Link per gli ospiti<input readOnly value={typeof window==='undefined'?'':link(s)} onFocus={e=>e.target.select()}/></label><div className="actions"><button onClick={()=>copy(s)}>Copia link</button><a className="button secondary" target="_blank" rel="noopener" href={'/index.html?g='+s.id}>Apri guida</a><button className="secondary" onClick={()=>{setId(s.id);setName(s.name);setCheckin(s.checkin);setCheckout(s.checkout);window.scrollTo({top:0,behavior:'smooth'});}}>Modifica</button><button className="text-button" onClick={()=>setPendingDelete(s.id)}>Rimuovi</button></div>{pendingDelete===s.id&&<div className="delete-note"><p>Rimuovere la personalizzazione di {s.name}? Il link tornerà generico.</p><button disabled={busy} onClick={()=>remove(s)}>Sì, rimuovi</button> <button className="secondary" onClick={()=>setPendingDelete('')}>Mantieni</button></div>}</article>)}<Link className="general-link" href="/index.html">Apri la guida generale</Link></main>;
}
