// AUTO-GENERATO da scripts/build-content.mjs — non modificare a mano.
// Fonte: public/index.html (testi verbatim, 103 elementi).
import type { Lang } from "@/lib/i18n";

export const contentGenerated: Record<string, Record<Lang, string>> = {
  "index_000": {"it":"Guida ospiti","en":"Guest guide","es":"Guía para huéspedes","fr":"Guide des invités","de":"Gäste-Guide"},
  "index_001": {"it":"A Casa di Marco","en":"A Casa di Marco","es":"A Casa di Marco","fr":"A Casa di Marco","de":"A Casa di Marco"},
  "index_002": {"it":"Garden Cottage Escape · Salerno","en":"Garden Cottage Escape · Salerno","es":"Garden Cottage Escape · Salerno","fr":"Garden Cottage Escape · Salerno","de":"Garden Cottage Escape · Salerno"},
  "index_003": {"it":"Benvenuti","en":"Welcome","es":"Bienvenidos","fr":"Bienvenue","de":"Willkommen"},
  "index_004": {"it":"Welcome · Bienvenidos · Bienvenue","en":"Welcome · Bienvenidos · Bienvenue","es":"Welcome · Bienvenidos · Bienvenue","fr":"Welcome · Bienvenidos · Bienvenue","de":"Welcome · Bienvenidos · Bienvenue"},
  "index_005": {"it":"Italiano","en":"Italian","es":"Italiano","fr":"Italien","de":"Italienisch"},
  "index_006": {"it":"English","en":"English","es":"Inglés","fr":"Anglais","de":"Englisch"},
  "index_007": {"it":"Español","en":"Spanish","es":"Español","fr":"Espagnol","de":"Spanisch"},
  "index_008": {"it":"Français","en":"French","es":"Francés","fr":"Français","de":"Französisch"},
  "index_009": {"it":"Deutsch","en":"German","es":"Alemán","fr":"Allemand","de":"Deutsch"},
  "index_010": {"it":"Guida per gli ospiti","en":"Guest Guide","es":"Guía para huéspedes","fr":"Guide des invités","de":"Gäste-Guide"},
  "index_011": {"it":"A Casa di Marco","en":"A Casa di Marco","es":"A Casa di Marco","fr":"A Casa di Marco","de":"A Casa di Marco"},
  "index_012": {"it":"Garden Cottage Escape · Salerno","en":"Garden Cottage Escape · Salerno","es":"Garden Cottage Escape · Salerno","fr":"Garden Cottage Escape · Salerno","de":"Garden Cottage Escape · Salerno"},
  "index_013": {"it":"Seleziona lingua","en":"Select language","es":"Selecciona idioma","fr":"Sélectionner la langue","de":"Sprache wählen"},
  "index_014": {"it":"🇮🇹 Italiano","en":"🇮🇹 Italian","es":"🇮🇹 Italiano","fr":"🇮🇹 Italien","de":"🇮🇹 Italienisch"},
  "index_015": {"it":"🇬🇧 English","en":"🇬🇧 English","es":"🇬🇧 Inglés","fr":"🇬🇧 Anglais","de":"🇬🇧 Englisch"},
  "index_016": {"it":"🇪🇸 Español","en":"🇪🇸 Spanish","es":"🇪🇸 Español","fr":"🇪🇸 Espagnol","de":"🇪🇸 Spanisch"},
  "index_017": {"it":"🇫🇷 Français","en":"🇫🇷 French","es":"🇫🇷 Francés","fr":"🇫🇷 Français","de":"🇫🇷 Französisch"},
  "index_018": {"it":"🇩🇪 Deutsch","en":"🇩🇪 German","es":"🇩🇪 Alemán","fr":"🇩🇪 Allemand","de":"🇩🇪 Deutsch"},
  "index_019": {"it":"Assistenza","en":"Help","es":"Ayuda","fr":"Assistance","de":"Hilfe"},
  "index_020": {"it":"Sezioni","en":"Sections","es":"Secciones","fr":"Rubriques","de":"Bereiche"},
  "index_021": {"it":"Per il tuo soggiorno","en":"For your stay","es":"Para tu estancia","fr":"Pour votre séjour","de":"Für euren Aufenthalt"},
  "index_022": {"it":"📲 Salva questa guida sul telefono","en":"📲 Save this guide on your phone","es":"📲 Guarda esta guía en tu teléfono","fr":"📲 Enregistrer ce guide sur le téléphone","de":"📲 Speichert diesen Guide auf dem Handy"},
  "index_023": {"it":"<strong>Android:</strong> apri il menu del browser ⋮ e scegli “Aggiungi alla schermata Home”. Verrà salvato un collegamento veloce al sito.","en":"<strong>Android:</strong> open the browser menu ⋮ and choose “Add to Home screen”. A quick shortcut to the website will be saved.","es":"<strong>Android:</strong> abre el menú del navegador ⋮ y elige “Añadir a pantalla de inicio”. Se guardará un acceso rápido al sitio.","fr":"<strong>Android :</strong> ouvrez le menu du navigateur ⋮ et choisissez “Ajouter à l’écran d’accueil”. Un raccourci rapide vers le site sera enregistré.","de":"<strong>Android:</strong> öffnet das Browsermenü ⋮ und wählt „Zum Startbildschirm hinzufügen“. Es wird eine Schnellverknüpfung zur Website gespeichert."},
  "index_024": {"it":"<strong>iPhone:</strong> apri il sito con Safari, premi Condividi e scegli “Aggiungi alla schermata Home”.","en":"<strong>iPhone:</strong> open the site with Safari, tap Share and choose “Add to Home Screen”.","es":"<strong>iPhone:</strong> abre el sitio con Safari, toca Compartir y elige “Añadir a pantalla de inicio”.","fr":"<strong>iPhone :</strong> ouvrez le site avec Safari, touchez Partager puis “Ajouter à l’écran d’accueil”.","de":"<strong>iPhone:</strong> öffnet die Website mit Safari, tippt auf Teilen und wählt „Zum Startbildschirm hinzufügen“."},
  "index_025": {"it":"Prima di arrivare","en":"Before arrival","es":"Antes de llegar","fr":"Avant l’arrivée","de":"Vor der Ankunft"},
  "index_026": {"it":"Sono in casa","en":"At the house","es":"Estoy en casa","fr":"À la maison","de":"Im Haus"},
  "index_027": {"it":"Prima di partire","en":"Before departure","es":"Antes de salir","fr":"Avant le départ","de":"Vor der Abreise"},
  "index_028": {"it":"Prima di arrivare","en":"Before arrival","es":"Antes de llegar","fr":"Avant l’arrivée","de":"Vor der Ankunft"},
  "index_029": {"it":"Arrivare senza pensieri","en":"A smooth arrival","es":"Llegar sin preocupaciones","fr":"Arriver sereinement","de":"Entspannt ankommen"},
  "index_030": {"it":"Prima del giorno del check-in, completate il check-in online: inviate i documenti e pagate la tassa di soggiorno e la cauzione. Senza la procedura completata, non troverete le chiavi nella KeyBox.","en":"Before check-in day, complete the online check-in: send your identity documents and pay the tourist tax and security deposit. If the procedure is incomplete, the keys will not be in the KeyBox.","es":"Antes del día del check-in, completad el check-in online: enviad los documentos y pagad la tasa turística y el depósito de garantía. Si la gestión no está completada, no encontraréis las llaves en la KeyBox.","fr":"Avant le jour de votre arrivée, terminez le check-in en ligne : envoyez les documents d’identité et payez la taxe de séjour et le dépôt de garantie. Si la procédure n’est pas terminée, les clés ne seront pas dans la KeyBox.","de":"Schließt vor dem Check-in-Tag den Online-Check-in ab: Sendet die Ausweisdokumente und bezahlt die Kurtaxe und die Kaution. Bei unvollständigem Check-in liegen die Schlüssel nicht in der KeyBox."},
  "index_031": {"it":"Problemi con la procedura o preferite il check-in in presenza? Scriveteci subito su WhatsApp. Il check-in in presenza va concordato e ha un costo che varia secondo la stagione.","en":"Having trouble with the procedure or prefer an in-person check-in? Message us immediately on WhatsApp. In-person check-in must be arranged and has a charge that varies by season.","es":"¿Problemas con el trámite o preferís el check-in presencial? Escribidnos inmediatamente por WhatsApp. El check-in presencial debe acordarse y tiene un coste que varía según la temporada.","fr":"Un problème avec la procédure ou vous préférez un accueil en personne ? Écrivez-nous immédiatement sur WhatsApp. Cet accueil doit être convenu et son coût varie selon la saison.","de":"Probleme mit dem Verfahren oder möchtet ihr persönlich einchecken? Schreibt uns sofort auf WhatsApp. Der persönliche Check-in muss vereinbart werden; die Kosten variieren je nach Saison."},
  "index_032": {"it":"Istruzioni di check-in","en":"Check-in instructions","es":"Instrucciones de check-in","fr":"Consignes d’arrivée","de":"Check-in-Anweisungen"},
  "index_033": {"it":"Scrivici su WhatsApp","en":"Message us on WhatsApp","es":"Escríbenos por WhatsApp","fr":"Écrivez-nous sur WhatsApp","de":"Schreibt uns auf WhatsApp"},
  "index_034": {"it":"Sono in casa","en":"At the house","es":"Estoy en casa","fr":"À la maison","de":"Im Haus"},
  "index_035": {"it":"Tutto per sentirti a casa","en":"Everything to feel at home","es":"Todo para sentirte en casa","fr":"Tout pour se sentir chez soi","de":"Alles, um sich zu Hause zu fühlen"},
  "index_036": {"it":"Leggete le regole della casa. Prima di usare qualcosa di cui non conoscete il funzionamento, consultate il manuale: contiene le spiegazioni delle dotazioni che non sono intuitive. Se non trovate un’istruzione o avete dubbi, scriveteci su WhatsApp.","en":"Please read the house rules. Before using anything unfamiliar, consult the manual: it explains equipment that is not intuitive. If an instruction is missing or you have questions, message us on WhatsApp.","es":"Leed las reglas de la casa. Antes de usar algo cuyo funcionamiento no conocéis, consultad el manual: explica los equipos que no son intuitivos. Si falta una instrucción o tenéis dudas, escribidnos por WhatsApp.","fr":"Lisez le règlement de la maison. Avant d’utiliser un équipement dont vous ne connaissez pas le fonctionnement, consultez le manuel : il explique les équipements moins intuitifs. S’il manque une instruction ou si vous avez un doute, écrivez-nous sur WhatsApp.","de":"Lest bitte die Hausregeln. Schaut vor der Nutzung unbekannter Geräte ins Handbuch: Es erklärt die weniger intuitiven Ausstattungen. Falls eine Anleitung fehlt oder ihr Fragen habt, schreibt uns auf WhatsApp."},
  "index_037": {"it":"Regole della casa","en":"House rules","es":"Reglas de la casa","fr":"Règlement de la maison","de":"Hausregeln"},
  "index_038": {"it":"Manuale della casa","en":"House manual","es":"Manual de la casa","fr":"Manuel de la maison","de":"Haushandbuch"},
  "index_039": {"it":"Prima di partire","en":"Before departure","es":"Antes de salir","fr":"Avant le départ","de":"Vor der Abreise"},
  "index_040": {"it":"Un check-out semplice","en":"An easy check-out","es":"Un check-out sencillo","fr":"Un départ tout simple","de":"Ein einfacher Check-out"},
  "index_041": {"it":"Prima di partire, seguite tutte le istruzioni di check-out e lasciate la casa in buone condizioni. Controllate la checklist, rispettate l’orario e lasciate le chiavi nella cassetta della posta “A Casa di Marco”, non nella KeyBox.","en":"Before leaving, follow all check-out instructions and leave the house in good condition. Check the checklist, respect the departure time and leave the keys in the “A Casa di Marco” letterbox, not in the KeyBox.","es":"Antes de salir, seguid todas las instrucciones de check-out y dejad la casa en buenas condiciones. Revisad la lista, respetad el horario y dejad las llaves en el buzón de correo “A Casa di Marco”, no en la KeyBox.","fr":"Avant de partir, suivez toutes les consignes de départ et laissez la maison en bon état. Vérifiez la checklist, respectez l’horaire et déposez les clés dans la boîte aux lettres « A Casa di Marco », pas dans la KeyBox.","de":"Befolgt vor der Abreise alle Check-out-Anweisungen und hinterlasst das Haus in gutem Zustand. Prüft die Checkliste, haltet die Abreisezeit ein und legt die Schlüssel in den Briefkasten „A Casa di Marco“, nicht in die KeyBox."},
  "index_042": {"it":"Checklist di check-out","en":"Check-out checklist","es":"Lista de check-out","fr":"Checklist de départ","de":"Check-out-Checkliste"},
  "index_043": {"it":"Scrivici su WhatsApp","en":"Message us on WhatsApp","es":"Escríbenos por WhatsApp","fr":"Écrivez-nous sur WhatsApp","de":"Schreibt uns auf WhatsApp"},
  "index_044": {"it":"Benvenuti","en":"Welcome","es":"Bienvenidos","fr":"Bienvenue","de":"Willkommen"},
  "index_045": {"it":"Hai bisogno di partire più tardi?","en":"Need to leave later?","es":"¿Necesitas salir más tarde?","fr":"Besoin de partir plus tard ?","de":"Möchtet ihr später abreisen?"},
  "index_046": {"it":"Queste sono le tariffe per una partenza più tardi: sceglietene una e concordatela con noi su WhatsApp.","en":"These are the rates for a later departure: pick one and agree it with us on WhatsApp.","es":"Estas son las tarifas para una salida más tarde: elegid una y acordadla con nosotros por WhatsApp.","fr":"Voici les tarifs pour un départ plus tardif : choisissez-en un et convenez-en avec nous sur WhatsApp.","de":"Das sind die Tarife für eine spätere Abreise: wählt eine aus und vereinbart sie mit uns per WhatsApp."},
  "index_047": {"it":"💬 Scrivici su WhatsApp","en":"💬 On WhatsApp","es":"💬 Por WhatsApp","fr":"💬 Sur WhatsApp","de":"💬 Per WhatsApp"},
  "index_048": {"it":"La guida, a modo tuo","en":"Your guide, your way","es":"Tu guía, a tu manera","fr":"Votre guide, à votre rythme","de":"Euer Guide, euer Tempo"},
  "index_049": {"it":"Check-in","en":"Check-in","es":"Check-in","fr":"Check-in","de":"Check-in"},
  "index_050": {"it":"Arrivo e accesso","en":"Arrival and access","es":"Llegada y acceso","fr":"Arrivée et accès","de":"Ankunft und Zugang"},
  "index_051": {"it":"Check-out","en":"Check-out","es":"Check-out","fr":"Check-out","de":"Check-out"},
  "index_052": {"it":"Prima di partire","en":"Before departure","es":"Antes de salir","fr":"Avant de partir","de":"Vor der Abreise"},
  "index_053": {"it":"La casa","en":"The house","es":"La casa","fr":"La maison","de":"Das Haus"},
  "index_054": {"it":"Wi-Fi e manuale","en":"Wi-Fi and manual","es":"Wi-Fi y manual","fr":"Wi-Fi et mode d’emploi","de":"WLAN und Hausbuch"},
  "index_055": {"it":"Regole","en":"House rules","es":"Normas","fr":"Règlement","de":"Hausregeln"},
  "index_056": {"it":"Un soggiorno sereno","en":"A comfortable stay","es":"Una estancia tranquila","fr":"Un séjour serein","de":"Ein angenehmer Aufenthalt"},
  "index_057": {"it":"Dove mangiare","en":"Where to eat","es":"Dónde comer","fr":"Où manger","de":"Essen gehen"},
  "index_058": {"it":"Ristoranti e locali","en":"Restaurants and cafés","es":"Restaurantes y bares","fr":"Restaurants et cafés","de":"Restaurants und Cafés"},
  "index_059": {"it":"Da scoprire","en":"Explore","es":"Descubrir","fr":"À découvrir","de":"Entdecken"},
  "index_060": {"it":"Salerno e dintorni","en":"Salerno and beyond","es":"Salerno y alrededores","fr":"Salerne et alentours","de":"Salerno und Umgebung"},
  "index_061": {"it":"Trasporti","en":"Transport","es":"Transporte","fr":"Transports","de":"Verkehr"},
  "index_062": {"it":"Bus, traghetti e taxi","en":"Buses, ferries and taxis","es":"Bus, ferris y taxis","fr":"Bus, ferries et taxis","de":"Bus, Fähren und Taxi"},
  "index_063": {"it":"La spesa","en":"Groceries","es":"La compra","fr":"Les courses","de":"Einkaufen"},
  "index_064": {"it":"Negozi vicini","en":"Nearby shops","es":"Tiendas cercanas","fr":"Commerces proches","de":"Geschäfte in der Nähe"},
  "index_065": {"it":"Colazione","en":"Breakfast","es":"Desayuno","fr":"Petit-déjeuner","de":"Frühstück"},
  "index_066": {"it":"Inizia la giornata","en":"Start your day","es":"Empieza el día","fr":"Commencez la journée","de":"Den Tag beginnen"},
  "index_067": {"it":"Parcheggi","en":"Parking","es":"Aparcamiento","fr":"Parking","de":"Parken"},
  "index_068": {"it":"A casa e in città","en":"At home and in town","es":"En casa y en la ciudad","fr":"À la maison et en ville","de":"Am Haus und in der Stadt"},
  "index_069": {"it":"Itinerario","en":"Itinerary","es":"Itinerario","fr":"Itinéraire","de":"Reiseplan"},
  "index_070": {"it":"Una giornata su misura","en":"A day your way","es":"Un día a tu medida","fr":"Une journée sur mesure","de":"Ein Tag nach euren Wünschen"},
  "index_071": {"it":"Farmacie e aiuto","en":"Pharmacies and help","es":"Farmacias y ayuda","fr":"Pharmacies et aide","de":"Apotheken und Hilfe"},
  "index_072": {"it":"Servizi ed emergenze","en":"Services and emergencies","es":"Servicios y emergencias","fr":"Services et urgences","de":"Dienste und Notfälle"},
  "index_073": {"it":"Meteo oggi a Salerno","en":"Today’s weather in Salerno","es":"Tiempo hoy en Salerno","fr":"Météo aujourd’hui à Salerne","de":"Wetter heute in Salerno"},
  "index_074": {"it":"Attenzione ombrellone","en":"Garden umbrella warning","es":"Atención sombrilla","fr":"Attention parasol","de":"Achtung Sonnenschirm"},
  "index_075": {"it":"In caso di pioggia o vento, vi chiediamo di chiudere l’ombrellone prima di uscire o quando non siete in giardino.","en":"In case of rain or wind, please close the garden umbrella before leaving or when you are not in the garden.","es":"En caso de lluvia o viento, os pedimos que cerréis la sombrilla antes de salir o cuando no estéis en el jardín.","fr":"En cas de pluie ou de vent, merci de refermer le parasol avant de sortir ou lorsque vous n’êtes pas dans le jardin.","de":"Bei Regen oder Wind bitten wir euch, den Sonnenschirm zu schließen, bevor ihr das Haus verlasst oder wenn ihr nicht im Garten seid."},
  "index_076": {"it":"Contatti","en":"Contacts","es":"Contactos","fr":"Contacts","de":"Kontakte"},
  "index_077": {"it":"Per comunicazioni urgenti potete chiamarci. Per tutte le altre richieste, scriveteci su WhatsApp: risponderemo il prima possibile.","en":"For urgent matters, you can call us. For all other requests, please message us on WhatsApp: we will reply as soon as possible.","es":"Para comunicaciones urgentes podéis llamarnos. Para todas las demás solicitudes, escribidnos por WhatsApp: responderemos lo antes posible.","fr":"Pour les communications urgentes, vous pouvez nous appeler. Pour toute autre demande, écrivez-nous sur WhatsApp : nous répondrons dès que possible.","de":"Bei dringenden Anliegen könnt ihr uns anrufen. Für alle anderen Anfragen schreibt uns bitte auf WhatsApp: Wir antworten so schnell wie möglich."},
  "index_078": {"it":"Vi chiediamo di utilizzare le chiamate solo per comunicazioni urgenti, così riusciamo a gestire al meglio tutte le richieste.","en":"Please use phone calls only for urgent matters, so we can manage all requests in the best possible way.","es":"Os pedimos que utilicéis las llamadas solo para asuntos urgentes, así podremos gestionar mejor todas las solicitudes.","fr":"Merci d'utiliser les appels uniquement pour les situations urgentes, afin que nous puissions gérer au mieux toutes les demandes.","de":"Wir bitten euch, Anrufe nur für dringende Anliegen zu nutzen, damit wir alle Anfragen bestmöglich bearbeiten können."},
  "index_079": {"it":"Contatto principale per il vostro soggiorno.","en":"Main contact for your stay.","es":"Contacto principal para vuestra estancia.","fr":"Contact principal pour votre séjour.","de":"Hauptkontakt für euren Aufenthalt."},
  "index_080": {"it":"📞 Chiama","en":"📞 Call","es":"📞 Llamar","fr":"📞 Appeler","de":"📞 Anrufen"},
  "index_081": {"it":"💬 WhatsApp","en":"💬 WhatsApp","es":"💬 WhatsApp","fr":"💬 WhatsApp","de":"💬 WhatsApp"},
  "index_082": {"it":"Secondo contatto utile in caso di necessità.","en":"Second useful contact if needed.","es":"Segundo contacto útil en caso de necesidad.","fr":"Deuxième contact utile en cas de besoin.","de":"Zweiter Kontakt im Bedarfsfall."},
  "index_083": {"it":"📞 Chiama","en":"📞 Call","es":"📞 Llamar","fr":"📞 Appeler","de":"📞 Anrufen"},
  "index_084": {"it":"💬 WhatsApp","en":"💬 WhatsApp","es":"💬 WhatsApp","fr":"💬 WhatsApp","de":"💬 WhatsApp"},
  "index_085": {"it":"Per comunicazioni non urgenti potete scriverci anche via email.","en":"For non-urgent communications, you can also email us.","es":"Para comunicaciones no urgentes, también podéis escribirnos por email.","fr":"Pour les communications non urgentes, vous pouvez aussi nous écrire par email.","de":"Für nicht dringende Anliegen könnt ihr uns auch per E-Mail schreiben."},
  "index_086": {"it":"✉️ Scrivi email","en":"✉️ Send email","es":"✉️ Enviar email","fr":"✉️ Envoyer un email","de":"✉️ E-Mail schreiben"},
  "index_087": {"it":"Numeri di emergenza","en":"Emergency numbers","es":"Números de emergencia","fr":"Numéros d'urgence","de":"Notrufnummern"},
  "index_088": {"it":"In caso di emergenza sanitaria chiamare il 118. Per emergenze generali chiamare il 112.","en":"In case of medical emergency, call 118. For general emergencies, call 112.","es":"En caso de emergencia sanitaria, llamad al 118. Para emergencias generales, llamad al 112.","fr":"En cas d'urgence médicale, appelez le 118. Pour les urgences générales, appelez le 112.","de":"Bei einem medizinischen Notfall ruft 118 an. Für allgemeine Notfälle ruft 112 an."},
  "index_089": {"it":"🚑 Chiama 118","en":"🚑 Call 118","es":"🚑 Llamar 118","fr":"🚑 Appeler 118","de":"🚑 118 anrufen"},
  "index_090": {"it":"🚨 Chiama 112","en":"🚨 Call 112","es":"🚨 Llamar 112","fr":"🚨 Appeler 112","de":"🚨 112 anrufen"},
  "index_091": {"it":"Chi è Marco?","en":"Who is Marco?","es":"¿Quién es Marco?","fr":"Qui est Marco ?","de":"Wer ist Marco?"},
  "index_092": {"it":"Gentili Ospiti,","en":"Dear Guests,","es":"Queridos huéspedes:","fr":"Chers hôtes,","de":"Liebe Gäste,"},
  "index_093": {"it":"Forse avrete notato che prima di arrivare qui non avete mai parlato o chattato con Marco. E magari vi stareste chiedendo: “Sì, ma chi è Marco?” La verità è semplice... Questa casa non è gestita da Marco. È dedicata a lui.","en":"Perhaps you may have noticed that before arriving here, you never actually spoke or chatted with Marco. And maybe you are wondering: “Yes, but who is Marco?” The truth is simple... This house is not managed by Marco. It is dedicated to him.","es":"Quizá habréis notado que antes de llegar aquí nunca hablasteis ni chateasteis con Marco. Y tal vez os estaréis preguntando: “Sí, pero ¿quién es Marco?” La verdad es muy sencilla... Esta casa no está gestionada por Marco. Está dedicada a él.","fr":"Vous avez peut-être remarqué qu’avant d’arriver ici, vous n’avez jamais parlé ni échangé de messages avec Marco. Et vous vous demandez peut-être : « Oui, mais qui est Marco ? » La vérité est simple... Cette maison n’est pas gérée par Marco. Elle lui est dédiée.","de":"Vielleicht ist euch aufgefallen, dass ihr, bevor ihr hier angekommen seid, nie wirklich mit Marco gesprochen oder geschrieben habt. Und vielleicht fragt ihr euch: „Ja, aber wer ist Marco?“ Die Wahrheit ist einfach... Dieses Haus wird nicht von Marco verwaltet. Es ist ihm gewidmet."},
  "index_094": {"it":"Marco era nostro zio... Non viveva qui, ma con noi, ed era un po’ come un fratello maggiore. Era una capa fresca, smemorato, disorganizzato e capatosta come pochi, ma sempre allegro e con il sorriso facile. Lavorava tanto, a modo suo, e mangiare bene per lui non era mai abbastanza. Per il suo aspetto imponente e affettuoso lo chiamavamo affettuosamente “bambolotto”.","en":"Marco was our uncle... He did not live here, but with us, and he was a bit like an older brother. He was free-spirited, forgetful, disorganised and stubborn like few others, but always cheerful and quick to smile. He worked hard, in his own way, and good food was never enough for him. Because of his big and affectionate presence, we lovingly called him “bambolotto”.","es":"Marco era nuestro tío... No vivía aquí, sino con nosotras, y era un poco como un hermano mayor. Era una persona despreocupada, olvidadiza, desorganizada y muy testaruda, pero siempre alegre y con una sonrisa fácil. Trabajaba mucho, a su manera, y para él comer bien nunca era suficiente. Por su presencia imponente y cariñosa, le llamábamos con cariño “bambolotto”.","fr":"Marco était notre oncle... Il ne vivait pas ici, mais avec nous, et il était un peu comme un grand frère. Il était insouciant, distrait, désorganisé et têtu comme peu de gens, mais toujours joyeux et avec le sourire facile. Il travaillait beaucoup, à sa manière, et pour lui, bien manger n’était jamais assez. Pour sa présence imposante et affectueuse, nous l’appelions tendrement « bambolotto ».","de":"Marco war unser Onkel... Er lebte nicht hier, sondern bei uns, und er war ein bisschen wie ein großer Bruder. Er war sorglos, vergesslich, unorganisiert und störrisch wie nur wenige, aber immer fröhlich und mit einem leichten Lächeln. Er arbeitete viel, auf seine Weise, und gutes Essen war ihm nie genug. Wegen seiner imposanten und liebevollen Erscheinung nannten wir ihn liebevoll „bambolotto“."},
  "index_095": {"it":"Purtroppo Marco non è più con noi, ma questa casa è un modo per tenerlo vicino e ricordarlo ogni giorno. Aprire una casa come questa era uno dei suoi sogni, e noi l’abbiamo fatto anche per lui.","en":"Sadly, Marco is no longer with us, but this house is a way to keep him close and remember him every day. Opening a home like this was one of his dreams, and we did it for him too.","es":"Por desgracia, Marco ya no está con nosotras, pero esta casa es una forma de tenerlo cerca y recordarlo cada día. Abrir una casa como esta era uno de sus sueños, y también lo hicimos por él.","fr":"Malheureusement, Marco n’est plus avec nous, mais cette maison est une façon de le garder près de nous et de nous souvenir de lui chaque jour. Ouvrir une maison comme celle-ci était l’un de ses rêves, et nous l’avons fait aussi pour lui.","de":"Leider ist Marco nicht mehr bei uns, aber dieses Haus ist eine Möglichkeit, ihn nahe zu haben und jeden Tag an ihn zu erinnern. Ein Haus wie dieses zu eröffnen war einer seiner Träume, und wir haben es auch für ihn getan."},
  "index_096": {"it":"E a volte sembra proprio che Marco venga a farci visita… Se durante il vostro soggiorno vedete un pettirosso avvicinarsi alla casa, non spaventatelo. Ci capita spesso, a volte quando scendiamo a pulire oppure quando passiamo un pomeriggio qui... Non si fa toccare, ma a volte entra persino in casa.","en":"And sometimes it really feels as if Marco comes to visit us… If during your stay you see a robin coming close to the house, please do not scare it away. It happens quite often, sometimes when we come down to clean or spend an afternoon here... It does not let itself be touched, but sometimes it even comes inside the house.","es":"Y a veces realmente parece que Marco venga a visitarnos… Si durante vuestra estancia veis un petirrojo acercarse a la casa, no lo asustéis. Nos pasa a menudo, a veces cuando bajamos a limpiar o cuando pasamos aquí una tarde... No se deja tocar, pero a veces incluso entra en casa.","fr":"Et parfois, on a vraiment l’impression que Marco vient nous rendre visite… Si pendant votre séjour vous voyez un rouge-gorge s’approcher de la maison, ne l’effrayez pas. Cela nous arrive souvent, parfois quand nous descendons pour nettoyer ou quand nous passons un après-midi ici... Il ne se laisse pas toucher, mais il entre parfois même dans la maison.","de":"Und manchmal scheint es wirklich, als käme Marco uns besuchen... Wenn ihr während eures Aufenthalts ein Rotkehlchen seht, das sich dem Haus nähert, erschreckt es nicht. Das passiert uns oft, manchmal wenn wir zum Putzen herunterkommen oder einen Nachmittag hier verbringen... Es lässt sich nicht anfassen, aber manchmal kommt es sogar ins Haus."},
  "index_097": {"it":"Per il suo comportamento e anche per il suo aspetto chiatto, ci è venuto naturale pensare, nonostante siamo persone poco superstiziose, che sia Marco che passa a dare un’occhiata e a controllare che sia tutto a posto. Lo chiamiamo affettuosamente “il pettirosso chiatto”, perché anche lui, come nostro zio, non era certo uno che si teneva leggero.","en":"Because of its behaviour and even its plump appearance, it felt natural to think — even though we are not very superstitious people — that it might be Marco stopping by to check that everything is all right. We lovingly call it “the chubby robin”, because, just like our uncle, he was certainly not someone who stayed skinny.","es":"Por su comportamiento y también por su aspecto regordete, nos vino natural pensar, aunque no somos personas supersticiosas, que era Marco pasando a echar un vistazo y comprobar que todo estaba bien. Lo llamamos cariñosamente “el petirrojo gordito”, porque él también, como nuestro tío, no era precisamente de los que se mantenían ligeros.","fr":"À cause de son comportement et même de son aspect un peu dodu, il nous est venu naturellement à l’esprit, même si nous ne sommes pas très superstitieuses, que c’était Marco qui passait jeter un coup d’œil pour vérifier que tout allait bien. Nous l’appelons affectueusement « le rouge-gorge dodu », car lui aussi, comme notre oncle, n’était pas vraiment du genre à rester léger.","de":"Wegen seines Verhaltens und auch seines pummeligen Aussehens lag es für uns nahe zu denken, obwohl wir keine sehr abergläubischen Menschen sind, dass Marco vorbeikommt, um nachzusehen und zu prüfen, dass alles in Ordnung ist. Wir nennen es liebevoll „das pummelige Rotkehlchen“, denn auch er, wie unser Onkel, war sicherlich keiner, der auf sein Gewicht achtete."},
  "index_098": {"it":"Se lo vedete, se vi va, potete anche mandarci una foto, ci farà sorridere pensare che Marco sia passato a trovarvi. Se qui vi sentirete bene, se vi sembrerà davvero di essere a casa, allora probabilmente Marco è passato. Ha guardato in giro, ha borbottato qualcosa… e se n’è andato soddisfatto.","en":"If you see it, and if you feel like it, you can also send us a photo — it will make us smile to think that Marco stopped by to visit you. If you feel good here, if it truly feels like home, then Marco has probably passed by. He looked around, grumbled about something… and left satisfied.","es":"Si lo veis, y si os apetece, también podéis enviarnos una foto: nos hará sonreír pensar que Marco ha pasado a visitaros. Si aquí os sentís bien, si de verdad os parece estar en casa, entonces probablemente Marco ha pasado por aquí. Ha mirado alrededor, ha gruñido algo… y se ha ido satisfecho.","fr":"Si vous le voyez, et si vous en avez envie, vous pouvez aussi nous envoyer une photo : cela nous fera sourire de penser que Marco est passé vous rendre visite. Si vous vous sentez bien ici, si vous avez vraiment l’impression d’être chez vous, alors Marco est probablement passé. Il a regardé autour de lui, a marmonné quelque chose… puis il est reparti satisfait.","de":"Wenn ihr es seht und Lust habt, könnt ihr uns auch ein Foto schicken — es wird uns zum Lächeln bringen zu denken, dass Marco bei euch vorbeigekommen ist. Wenn ihr euch hier wohlfühlt, wenn es sich wirklich wie zu Hause anfühlt, dann ist Marco wahrscheinlich vorbeigekommen. Er hat sich umgesehen, etwas vor sich hin gemurmelt… und ist zufrieden gegangen."},
  "index_099": {"it":"— Stefania, Ambra, Asja","en":"— Stefania, Ambra, Asja","es":"— Stefania, Ambra, Asja","fr":"— Stefania, Ambra, Asja","de":"— Stefania, Ambra, Asja"},
  "index_100": {"it":"Il nostro “pettirosso chiatto”. Se lo vedete, mandateci una foto 💛","en":"Our “chubby robin”. If you see it, send us a photo 💛","es":"Nuestro “petirrojo gordito”. Si lo veis, enviadnos una foto 💛","fr":"Notre « rouge-gorge dodu ». Si vous le voyez, envoyez-nous une photo 💛","de":"Unser „pummeliges Rotkehlchen“. Wenn ihr es seht, schickt uns ein Foto 💛"},
  "index_101": {"it":"<strong>A Casa di Marco – Guida ospiti</strong> · Garden Cottage Escape · Salerno","en":"<strong>A Casa di Marco – Guest Guide</strong> · Garden Cottage Escape · Salerno","es":"<strong>A Casa di Marco – Guía para huéspedes</strong> · Garden Cottage Escape · Salerno","fr":"<strong>A Casa di Marco – Guide des invités</strong> · Garden Cottage Escape · Salerno","de":"<strong>A Casa di Marco – Gäste-Guide</strong> · Garden Cottage Escape · Salerno"},
  "index_102": {"it":"Grazie per aver scelto la nostra casa.","en":"Thank you for choosing our home.","es":"Gracias por elegir nuestra casa.","fr":"Merci d'avoir choisi notre maison.","de":"Danke, dass ihr unser Haus gewählt habt."},
};

export const contentIsHtml: Record<string, boolean> = {
  "index_000": false,
  "index_001": false,
  "index_002": false,
  "index_003": false,
  "index_004": false,
  "index_005": false,
  "index_006": false,
  "index_007": false,
  "index_008": false,
  "index_009": false,
  "index_010": false,
  "index_011": false,
  "index_012": false,
  "index_013": false,
  "index_014": false,
  "index_015": false,
  "index_016": false,
  "index_017": false,
  "index_018": false,
  "index_019": false,
  "index_020": false,
  "index_021": false,
  "index_022": false,
  "index_023": true,
  "index_024": true,
  "index_025": false,
  "index_026": false,
  "index_027": false,
  "index_028": false,
  "index_029": false,
  "index_030": false,
  "index_031": false,
  "index_032": false,
  "index_033": false,
  "index_034": false,
  "index_035": false,
  "index_036": false,
  "index_037": false,
  "index_038": false,
  "index_039": false,
  "index_040": false,
  "index_041": false,
  "index_042": false,
  "index_043": false,
  "index_044": false,
  "index_045": false,
  "index_046": false,
  "index_047": false,
  "index_048": false,
  "index_049": false,
  "index_050": false,
  "index_051": false,
  "index_052": false,
  "index_053": false,
  "index_054": false,
  "index_055": false,
  "index_056": false,
  "index_057": false,
  "index_058": false,
  "index_059": false,
  "index_060": false,
  "index_061": false,
  "index_062": false,
  "index_063": false,
  "index_064": false,
  "index_065": false,
  "index_066": false,
  "index_067": false,
  "index_068": false,
  "index_069": false,
  "index_070": false,
  "index_071": false,
  "index_072": false,
  "index_073": false,
  "index_074": false,
  "index_075": false,
  "index_076": false,
  "index_077": false,
  "index_078": false,
  "index_079": false,
  "index_080": false,
  "index_081": false,
  "index_082": false,
  "index_083": false,
  "index_084": false,
  "index_085": false,
  "index_086": false,
  "index_087": false,
  "index_088": false,
  "index_089": false,
  "index_090": false,
  "index_091": false,
  "index_092": false,
  "index_093": false,
  "index_094": false,
  "index_095": false,
  "index_096": false,
  "index_097": false,
  "index_098": false,
  "index_099": false,
  "index_100": false,
  "index_101": true,
  "index_102": false,
};
