// AUTO-GENERATO da scripts/build-legacy-pages.mjs — non modificare a mano.
// Fonte: public/mangiare.html (<main> verbatim, 5 lingue).
import type { Lang } from "@/lib/i18n";

export const slug = "mangiare";

export const title: Record<Lang, string> = {"it":"Dove mangiare","en":"Where to eat","es":"Dónde comer","fr":"Où manger","de":"Wo ihr essen könnt"};

export const html: Record<Lang, string> = {
  it: "<section id=\"food-start\">\r\n<h2>Cosa hai voglia di mangiare?</h2>\r\n<p>Scegli una categoria e scopri i nostri consigli da salernitani.</p>\r\n<p class=\"price-legend\">Legenda prezzi: € economico · €€ medio · €€€ costoso</p>\r\n\r\n<div class=\"delivery-note\">\r\n<strong>🛵 Ordina a domicilio</strong>\r\n<p>Potete ordinare con <strong>Deliveroo</strong>, <strong>Just Eat</strong> o altre piattaforme. Inserite l’indirizzo qui sotto e fatevi portare la consegna al <strong>cancello condominiale</strong>, non all’ingresso dell’abitazione. Se il rider entra nel condominio, ricordatevi di riaprirgli il cancello per farlo uscire.</p>\r\n<div class=\"address\">\r\n          📍 Via Brignano Inferiore 69, Parco Sala, Salerno\r\n        </div>\r\n</div>\r\n</section>",
  en: "<section id=\"food-start\">\r\n<h2>What would you like to eat?</h2>\r\n<p>Choose a category and discover our local recommendations.</p>\r\n<p class=\"price-legend\">Price guide: € budget · €€ medium · €€€ expensive</p>\r\n\r\n<div class=\"delivery-note\">\r\n<strong>🛵 Order food delivery</strong>\r\n<p>You can order with <strong>Deliveroo</strong>, <strong>Just Eat</strong> or other apps. Use the address below and have it delivered to the <strong>condominium gate</strong>, not the apartment entrance. If the rider enters the complex, remember to open the gate to let them out.</p>\r\n<div class=\"address\">\r\n          📍 Via Brignano Inferiore 69, Parco Sala, Salerno\r\n        </div>\r\n</div>\r\n</section>",
  es: "<section id=\"food-start\">\r\n<h2>¿Qué te apetece comer?</h2>\r\n<p>Elige una categoría y descubre nuestras recomendaciones locales.</p>\r\n<p class=\"price-legend\">Precios: € económico · €€ medio · €€€ caro</p>\r\n\r\n<div class=\"delivery-note\">\r\n<strong>🛵 Pide a domicilio</strong>\r\n<p>Podéis pedir con <strong>Deliveroo</strong>, <strong>Just Eat</strong> u otras plataformas. Usad la dirección de abajo y pedid la entrega en la <strong>cancela del condominio</strong>, no en la puerta de la casa. Si el rider entra en el residencial, abridle la cancela para que pueda salir.</p>\r\n<div class=\"address\">\r\n          📍 Via Brignano Inferiore 69, Parco Sala, Salerno\r\n        </div>\r\n</div>\r\n</section>",
  fr: "<section id=\"food-start\">\r\n<h2>Qu’avez-vous envie de manger ?</h2>\r\n<p>Choisissez une catégorie et découvrez nos recommandations locales.</p>\r\n<p class=\"price-legend\">Prix : € économique · €€ moyen · €€€ cher</p>\r\n\r\n<div class=\"delivery-note\">\r\n<strong>🛵 Commandez à domicile</strong>\r\n<p>Vous pouvez commander avec <strong>Deliveroo</strong>, <strong>Just Eat</strong> ou d’autres plateformes. Utilisez l’adresse ci-dessous et faites-vous livrer au <strong>portail de la copropriété</strong>, pas à la porte du logement. Si le livreur entre dans la résidence, rouvrez-lui le portail pour qu’il puisse sortir.</p>\r\n<div class=\"address\">\r\n          📍 Via Brignano Inferiore 69, Parco Sala, Salerno\r\n        </div>\r\n</div>\r\n</section>",
  de: "<section id=\"food-start\">\r\n<h2>Worauf habt ihr Appetit?</h2>\r\n<p>Wählt eine Kategorie und entdeckt unsere Tipps aus Salerno.</p>\r\n<p class=\"price-legend\">Preisübersicht: € günstig · €€ mittel · €€€ teuer</p>\r\n\r\n<div class=\"delivery-note\">\r\n<strong>🛵 Lieferung bestellen</strong>\r\n<p>Ihr könnt mit <strong>Deliveroo</strong>, <strong>Just Eat</strong> oder anderen Plattformen bestellen. Gebt unten die Adresse ein und lasst euch die Lieferung an das <strong>Tor der Wohnanlage</strong> bringen, nicht an den Eingang der Wohnung. Wenn der Fahrer in die Wohnanlage kommt, denkt daran, ihm das Tor zum Hinausgehen wieder zu öffnen.</p>\r\n<div class=\"address\">\r\n          📍 Via Brignano Inferiore 69, Parco Sala, Salerno\r\n        </div>\r\n</div>\r\n</section>",
};
