// AUTO-GENERATO da scripts/build-legacy-pages.mjs — non modificare a mano.
// Fonte: public/regole.html (<main> verbatim, 5 lingue).
import type { Lang } from "@/lib/i18n";

export const slug = "regole";

export const title: Record<Lang, string> = {"it":"Regole della casa","en":"House rules","es":"Reglas de la casa","fr":"Règles de la maison","de":"Hausregeln"};

export const html: Record<Lang, string> = {
  it: "<section class=\"rules-page\"><h2>Regole della casa</h2><p class=\"rules-intro\">Per garantire un soggiorno piacevole a tutti e mantenere la casa nelle migliori condizioni, vi chiediamo di rispettare queste semplici regole.</p><div class=\"rules-highlights\"><div><span>Check-in</span><strong>Dalle 15:00</strong></div><div><span>Check-out</span><strong>Entro le 10:00</strong></div><div><span>Silenzio</span><strong>23:00–7:00</strong></div></div><aside class=\"deposit-note\"><h3>Deposito cauzionale</h3><p>Gli eventuali importi dovuti per ritardi non concordati, smarrimento delle chiavi, smaltimento straordinario dei rifiuti, pulizie straordinarie o danni imputabili all’ospite potranno essere trattenuti dal deposito cauzionale, come indicato nelle regole qui sotto.</p></aside><p class=\"rules-thanks\">Grazie per la collaborazione e buon soggiorno ad A Casa di Marco! 🏡</p></section>",
  en: "<section class=\"rules-page\"><h2>House rules</h2><p class=\"rules-intro\">To ensure an enjoyable stay for everyone and keep the house in the best condition, please follow these simple rules.</p><div class=\"rules-highlights\"><div><span>Check-in</span><strong>From 15:00</strong></div><div><span>Check-out</span><strong>By 10:00</strong></div><div><span>Quiet hours</span><strong>23:00–7:00</strong></div></div><aside class=\"deposit-note\"><h3>Security deposit</h3><p>Any amounts due for unagreed delays, lost keys, exceptional waste disposal, extra cleaning or damage attributable to the guest may be deducted from the security deposit, as described below.</p></aside><p class=\"rules-thanks\">Thank you for your cooperation and enjoy your stay at A Casa di Marco! 🏡</p></section>",
  es: "<section class=\"rules-page\"><h2>Reglas de la casa</h2><p class=\"rules-intro\">Para garantizar una estancia agradable para todos y mantener la casa en las mejores condiciones, respetad estas sencillas reglas.</p><div class=\"rules-highlights\"><div><span>Check-in</span><strong>Desde las 15:00</strong></div><div><span>Check-out</span><strong>Antes de las 10:00</strong></div><div><span>Silencio</span><strong>23:00–7:00</strong></div></div><aside class=\"deposit-note\"><h3>Depósito de garantía</h3><p>Los importes debidos por retrasos no acordados, pérdida de llaves, eliminación extraordinaria de residuos, limpieza extraordinaria o daños imputables al huésped podrán deducirse del depósito de garantía, según las reglas siguientes.</p></aside><p class=\"rules-thanks\">¡Gracias por colaborar y feliz estancia en A Casa di Marco! 🏡</p></section>",
  fr: "<section class=\"rules-page\"><h2>Règles de la maison</h2><p class=\"rules-intro\">Pour garantir un séjour agréable à tous et préserver la maison, merci de respecter ces règles simples.</p><div class=\"rules-highlights\"><div><span>Check-in</span><strong>Dès 15 h</strong></div><div><span>Check-out</span><strong>Avant 10 h</strong></div><div><span>Calme</span><strong>23:00–7:00</strong></div></div><aside class=\"deposit-note\"><h3>Dépôt de garantie</h3><p>Les montants dus pour retards non convenus, perte de clés, élimination exceptionnelle des déchets, ménage exceptionnel ou dégâts imputables au voyageur pourront être retenus sur le dépôt de garantie, selon les règles ci-dessous.</p></aside><p class=\"rules-thanks\">Merci pour votre coopération et bon séjour à A Casa di Marco ! 🏡</p></section>",
  de: "<section class=\"rules-page\"><h2>Hausregeln</h2><p class=\"rules-intro\">Damit alle einen angenehmen Aufenthalt haben und das Haus in bestem Zustand bleibt, bitten wir euch, diese einfachen Regeln zu beachten.</p><div class=\"rules-highlights\"><div><span>Check-in</span><strong>Ab 15:00</strong></div><div><span>Check-out</span><strong>Bis 10:00</strong></div><div><span>Ruhe</span><strong>23:00–7:00</strong></div></div><aside class=\"deposit-note\"><h3>Kaution</h3><p>Fällige Beträge für nicht vereinbarte Verspätungen, verlorene Schlüssel, außergewöhnliche Müllentsorgung oder Reinigung sowie vom Gast verursachte Schäden können entsprechend den folgenden Regeln von der Kaution einbehalten werden.</p></aside><p class=\"rules-thanks\">Vielen Dank für eure Mithilfe und einen schönen Aufenthalt in A Casa di Marco! 🏡</p></section>",
};
